carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home 

app_name = 'carts'

urlpatterns = [
    path("", cart_home, name='cart_home'),
    path("update/", cart_update, name='cart_update'),
    path("checkout/", checkout_home, name='checkout_home'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product.views import change_language

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls' , namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include('carts.urls' , namespace='cart')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),


    # path("", include("django.contrib.auth.urls")),

    path('change-language/', change_language, name='change-language'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from decimal import Decimal
from product.models import Product
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save, m2m_changed

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                    cart_obj.user = request.user
                    cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj
    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)    


class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects     = CartManager()

    def __str__(self):
        return str(self.id)
    

def m2m_changed_cart_receiver(sender, instance,action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':

        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        instance.subtotal = total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)



def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08) # 7%
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cart
from product.models import Product
from orders.models import Order
from accounts.forms import RegisterForm
from billing.models import BillingProfile

# Create your views here.
# def cart_creater(user=None):
#     cart_obj = Cart.objects.create(user=None)
#     print("Create New Cart")
#     return cart_obj

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    # products = cart_obj.products.all()
    # total = 0
    # for x in products:
    #     total += x.price
    # cart_obj.total = total
    # cart_obj.save()
    return render(request, 'cart.html',{"cart":cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect("cart:cart_home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    
    return redirect("cart:cart_home")

def checkout_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    order_obj = None
    if new_obj or Cart.objects.count() == 0:
        return redirect("cart:cart_home")
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    
    user = request.user
    billing_profile = None
    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(
            user=user, email=user.email
        )
    context = {
        "object":order_obj,
        "billing_profile":billing_profile,
    }
    return render(request, 'checkout.html', context)

carts/templates/cart.html
{% extends "base.html" %}

{% block content %}
    <h1>cart</h1>
    
    {% if cart.products.exists %}
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product name</th>
      <th scope="col">Product price</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
      {% for product in cart.products.all %}
        
      
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{{ product.get_absolute_url }}" class="btn btn-light">{{ product.title }}</a></td>
      <td>{{ product.price }}</td>
    <td>{% include 'cart_edit.html' with product=product cart=cart %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<h3 colspan="3">Subtotal : {{ cart.subtotal }}</h3>
<h3 colspan="3">Total : {{ cart.total }}</h3>
<h3 colspan="3" class="btn btn-success"><a href="{% url 'cart:checkout_home' %}">Checkout</a></h3>
{% else %}
<p class="lead">Cart is empty</p>
    {% endif %}
        
{% endblock content %}
    

carts/templates/cart_edit.html
<form method="POST" action="{% url 'cart:cart_update' %}" class="form">{% csrf_token %}
    <div class="col-12">
        <input type="hidden" name="product_id" value="{{product.id}}"/>
        <button type="submit" class="btn btn-danger">remove product</button>
    </div>
</form>

carts/templates/checkout.html
{% extends "base.html" %}

{% block content %}

{% if not billing_profile %}
<div class="container"> 
        <div class="row text-center">
                <div class="col-12 col-md-6">
                        <a href="{% url 'accounts:login' %}?next={{request.path}}">Login</a> 
                </div>
                <div class="col-12 col-md-6">
                        Continue as Guest
                </div>
        </div>
</div>

{% else %}
        <div class="container">
                <h1>Checkout</h1>
                <p>Cart total : {{object.cart.total}}</p>
                <p>Shipping total : {{object.shipping_total}}</p>
                <p>Total : {{object.total}}</p>

        </div>

{% endif %}
{% endblock content %}
    

carts/templates/update_cart.html
<form method="POST" action="{% url 'cart:cart_update' %}" class="form">{% csrf_token %}
    <div class="col-12">
        <input type="hidden" name="product_id" value="{{product.id}}"/>
        {% if product in cart.products.all %}
            <button type="submit" class="btn btn-danger">remove product</button> 
        {% else %}
        <button type="submit" class="btn btn-success">add to cart</button>
        {% endif %}
    </div>
</form>