accounts/urls.py
from django.urls import path, include
from .views import RegisterView
app_name = 'accounts'

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("register/", RegisterView.as_view(), name="register"),
]

carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home 

app_name = 'carts'

urlpatterns = [
    path("", cart_home, name='cart_home'),
    path("update/", cart_update, name='cart_update'),
    path("checkout/", checkout_home, name='checkout_home'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from product.views import change_language

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls' , namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include('carts.urls' , namespace='cart')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),


    # path("", include("django.contrib.auth.urls")),

    path('change-language/', change_language, name='change-language'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, product_list_view, product_detail_view

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('fbv/', product_list_view),

    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('fbv/<int:pk>/', product_detail_view),
]

templates/snippets/card.html
{% load i18n %}
<div class="card" style="width: 18rem;">
    {% if obj.image %}
    <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.title}}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{obj.title}}</h5>
        <p class="card-text">{{obj.description}}</p>
        <a href="{{obj.get_absolute_url}}" class="btn btn-primary">{% trans "Go somewhere" %}</a>
    </div>
</div>

templates/snippets/cdn.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
<script src="{% static 'js/jscolor.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

templates/snippets/nav.html
{% load i18n %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <a class="navbar-brand" href="{% url 'products:list' %}">{% trans "Navbar" %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <a class="nav-link" href="#">{% trans 'Home' %} <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">{% trans 'Link' %}</a>
        </li>
        <li class="nav-item dropdown">
            {% if user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.username}}
            {% else %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans 'sign' %}
                {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            
            {% if user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'accounts:logout' %}?next={{request.path}}">{% trans 'Logout' %}</a>

            
                {% else %}
            <a class="dropdown-item" href="{% url 'accounts:login' %}?next={{request.path}}">{% trans 'Login' %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:register' %}">{% trans 'Register' %}</a>
            {% endif %}
        </div>
        </li>
        <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{% trans 'Disabled' %}</a>
        </li>
        <li class="nav-item">

            <a class="nav-link" href="{% url 'cart:cart_home' %}">
                <img src="{% static 'img/cart.png' %}" alt="jkbkj" style="width: 4%;">{{request.session.cart_items}}
            </a>
            </li>
    
    </ul>
    <a href="{% url 'change-language' %}">{% trans 'عربى' %}</a>
    {% include 'snippets/form-search.html' %}
    </div>
    </div>
</nav>